Create databasE tbl_QLHieuThuoc
usE tbl_QLHieuThuoc

GO
--bảng phụ combobox
--1
Create TABLE tbl_LOAI
(
	MaLoai int IDENTITY(1,1) NOT NULL,
	TenLoai NVARCHAR(30),
	CONSTRAINT PK_LOAI PRIMaRY KEY(MaLoai)
)

--bảng phụ combobox
--2
Create TABLE tbl_NHASANXUAT
(
	MaNSX int IDENTITY(1,1) NOT NULL,
	TenNSX NVARCHAR(30),
	CONSTRAINT PK_NHASANXUAT PRIMaRY KEY(MaNSX)
)
--3
Create tablE tbl_SANPHAM
(
	MaSP int IDENTITY(1,1) NOT NULL,
	TenSP NVARCHAR(50),
	ThanhPhan NVARCHAR(MaX),
	Gia float,
	MaNSX int NOT NULL,
	MaLoai int NOT NULL,
	HinhAnh varbinary(max),
	CONSTRAINT PK_SANPHAM PRIMaRY KEY(MaSP),
	CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY(MaLoai) REFERENCES tbl_LOAI(MaLoai),
	CONSTRAINT FK_SANPHAM_NHASANXUAT FOREIGN KEY(MaNSX) REFERENCES tbl_NHASANXUAT(MaNSX)
)
------------------------------------------------------
--4
Create TABLE tbl_KHO
(
	MaKho VARCHAR(5) NOT NULL,
	ViTri NVARCHAR(255),
	TenKho nvarchar(100),
	CONSTRAINT PK_KHO PRIMaRY KEY(MaKho)
)
--5
CREATE TABLE tbl_CHITIETHANGHOA
(
	MaCTSP varchar(10) not null,
	SoLuong int,
	HSD int,
	NSX datetime,
	MASP int not null,
	GiaNhap float,
	GiaBan float,
	MaKho varchar(5) not null,
	constraint PK_CHITIETHANGHOA primary key(MaCTSP),
	constraint FK_CHITIETHANGHOA_SANPHAM foreign key(MASP) references tbl_SANPHAM(MaSP),
	constraint FK_CHITIETHANGHA_KHO foreign key(MaKho) references tbl_KHO(MaKho)
)

--7
Create TABLE tbl_NHACUNGCAP
(
	MaNCC int IDENTITY(1,1) NOT NULL,
	TenNCC NVARCHAR(50),
	SDT VARCHAR(11),
	Email VARCHAR(50),
	DiaChi NVARCHAR(MaX),
	CONSTRAINT PK_NHACUNGCAP PRIMaRY KEY(MaNCC)
)

--8
Create TABLE tbl_KHACHHANG
(
	MaKH int IDENTITY(1,1) NOT NULL,
	TenKH NVARCHAR(50),
	SDT VARCHAR(11),
	DiaChi NVARCHAR(MaX),
	CONSTRAINT PK_KHACHHANG PRIMaRY KEY(MaKH)
)

--9
Create TABLE tbl_NGUOIDUNG
(
	--MaNGUOIDUNG VARCHAR(5) NOT NULL,
	TenDangNhap VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(50),
	QuanTri BIT NOT NULL,
	CONSTRAINT PK_NGUOIDUNG PRIMaRY KEY(TenDangNhap)
)
--10
Create TABLE tbl_DUOCSI
(
	MaDuocSi int IDENTITY(1,1) NOT NULL,
	TenDuocSi NVARCHAR(50),
	SDT VARCHAR(11),
	Email VARCHAR(50),
	DiaChi nvarchar(255),
	TenDangNhap VARCHAR(50) NOT NULL,
	CONSTRAINT PK_DUOCSI PRIMaRY KEY(MaDuocSi),
	constraint FK_DUOCSI_NGUOIDUNG FOREIGN KEY(TenDangNhap) references tbl_NGUOIDUNG(TenDangNhap)
)
--11
Create TABLE tbl_HOADON
(
	MaHD varchar(10) NOT NULL,
	MaDuocSi int NOT NULL,
	NgayLap DATE,
	TongTien float,
	MaKH int NOT NULL,
	Thang int,
	Nam int,
	CONSTRAINT PK_HOADON PRIMaRY KEY(MaHD),
	CONSTRAINT FK_HOADON_DUOCSI FOREIGN KEY(MaDuocSi) REFERENCES tbl_DUOCSI(MaDuocSi),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MaKH) REFERENCES tbl_KHACHHANG(MaKH)
)
--12
Create TABLE tbl_CTHOADON
(
	MaCTHD varchar(20) not null,
	MaHD VARCHAR(10) NOT NULL,
	MaCTSP varchar(10) not null,
	SoLuong INT,
	DonGia float,
	CONSTRAINT PK_CTHOADON PRIMaRY KEY(MaCTHD),
	CONSTRAINT FK_CTHOADON_HOADON FOREIGN KEY(MaHD) REFERENCES tbl_HOADON(MaHD),
	CONSTRAINT FK_CTHOADON_CHITIETHANGHOA FOREIGN KEY(MaCTSP) REFERENCES tbl_CHITIETHANGHOA(MaCTSP)
)


--13
Create TABLE tbl_PHIEUNHAP
(
	MaPN VARCHAR(10) NOT NULL,
	MaNCC int NOT NULL,
	MaDuocSi int NOT NULL,
	MaKho varchar(5) not null,
	NgayNhapHang DATETIME,
	TrangThai bit,
	CONSTRAINT PK_PHIEUNHAP PRIMaRY KEY(MaPN),
	CONSTRAINT FK_PHIEUNHAP_NHACUNGCAP FOREIGN KEY(MaNCC) REFERENCES tbl_NHACUNGCAP(MaNCC),
	CONSTRAINT FK_PHIEUNHAP_DUOCSI FOREIGN KEY(MaDuocSi) REFERENCES tbl_DUOCSI(MaDuocSi),
	constraint FK_PHIEUNHAP_KHO FOREIGN KEY(MaKho) REFERENCES tbl_KHO(MaKho)
)

--14
Create TABLE tbl_CTPHIEUNHAP
(
	MaCTPN varchar(20) not null,
	MaPN VARCHAR(10) NOT NULL,
	MACTSP varchar(10)  NOT NULL,
	NgayNhap datetime not null,
	TongTien float,
	CONSTRAINT PK_CTPHIEUNHAP PRIMaRY KEY(MaCTPN),
	CONSTRAINT FK_CTPHIEUNHAP_PHIEUNHAP FOREIGN KEY(MaPN) REFERENCES tbl_PHIEUNHAP(MaPN),
	CONSTRAINT FK_CTPHIEUNHAP_SANPHAM FOREIGN KEY(MaCTSP) REFERENCES tbl_CHITIETHANGHOA(MaCTSP)
)
